name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12.4'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
 

      # Step 4: Run linters and auto-fix issues
      - name: Run linter and auto-fix
        run: |
          pip install flake8 black
          flake8 src/scout_ml_package
          black src/scout_ml_package

      # Step 5: Commit auto-fixed changes
      - name: Commit auto-fixed changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'chore: auto-fix linting issues'
          github_token: ${{ secrets.G_TOKEN }}
#      # Step 5: Run tests (using pytest)
#      - name: Run tests
#        run: |
#          pip install pytest
#          pytest src/scout_ml_package/tests

#  deploy:
#    needs: build-and-test
#    runs-on: ubuntu-latest
#
#    steps:
#      # Step 1: Checkout the code
#      - name: Checkout code
#        uses: actions/checkout@v3
#
#      # Step 2: Deploy application (example)
#      - name: Deploy to production
#        run: |
#          echo "Deploying application..."
#          # Add deployment commands here (e.g., Docker, Kubernetes, etc.)

